server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://47.93.35.20:3306/wx_db?useUnicode=true&characterEncoding=utf8  
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
 